@startuml Authentification
'https://plantuml.com/use-case-diagram
left to right direction
actor Visiteur





package Authentification {
    usecase "Se connecter" as SignIn
    usecase "S'inscrire" as SignUp
}

Visiteur --> SignIn
Visiteur --> SignUp

SignUp ..>  SignIn : << extends >>

@enduml