@startuml
'https://plantuml.com/sequence-diagram

autonumber
actor Visiteur
actor Utilisateur
actor Systeme

Visiteur -> Systeme: Demande d'Authentication
Systeme --> Systeme: Authentication de l'utilisateur

loop
alt authentification valide
    Systeme --> Utilisateur: Redirige l'utilisateur vers la liste des figures
else authentification échoué
    Systeme --> Visiteur: Affiche le formulaire avec message d'erreur

else l'utilisateur s'inscrit
    Visiteur --> Systeme: Visiteur complète le formulaire
    Systeme --> Systeme: Verifie si cette l'utilisateur n'existe pas

    alt si l'utilisateur n'existe pas
        Systeme --> Systeme: Crée le compte de l'utilisateur
        Systeme --> Visiteur: Affiche message succès
       Utilisateur --> Systeme: Complète le formulaire de connexion
    else si l'utilisateur existe pas
        Systeme --> Visiteur: Affiche message d'erreur
    end
end

end


@enduml