@startuml
'https://plantuml.com/class-diagram

class Trick {
    id Integer
    name String
    description String
}

class CategoryTrick {
    id Integer
    name String
}

class Media {
    id Integer
    name String
    type String
    link String
}

class User {

}

@enduml